# Dependabot configuration file.
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2

enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "packages/mail"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/mail_aws_ses_node"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/mail_mailjet"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "packages/tekartik_mail_tk"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - autosubmit