name: tekartik_mail_mailjet
description: Email using mailjet http api
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  tekartik_mailjet:
    git:
      url: https://github.com/alextekartik/http_apis.dart
      path: packages/mailjet
      ref: dart3a
      version: '>=0.1.0'
  tekartik_mail:
    git:
      url: https://github.com/tekartik/mail.dart
      path: packages/mail
      ref: dart3a
dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0

dependency_overrides:
  tekartik_mail:
    path: ../mail
