name: tekartik_mail_tk
description: Tkmail api
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.1.4 <4.0.0'

# Add regular dependencies here.
dependencies:
  cv: '>=0.2.14'
  path:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart3a
    version: '>=0.5.5'
  tekartik_mail:
    git:
      url: https://github.com/tekartik/mail.dart
      path: packages/mail
      ref: dart3a

dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.21.0'
