name: tekartik_mail_tk
description: Tkmail api
version: 1.0.2
publish_to: none

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  cv: ">=1.1.0+4"
  path: ">=1.9.0"
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart3a
    version: '>=0.5.5'
  tekartik_mail:
    git:
      url: https://github.com/tekartik/mail.dart
      path: packages/mail
      ref: dart3a

dev_dependencies:
  lints: ">=5.0.0"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
  test: ">=1.24.0"
resolution: workspace

